var keyMirror = require('keymirror');

module.exports = keyMirror({
  COMMENTS_LOADING_START: null,
  COMMENTS_DATA: null,
  TAB_SWITCH_TODAY: null,
  TAB_SWITCH_YESTERDAY: null,
  TAB_SWITCH_THIS_WEEK: null,
  TAB_SWITCH_LAST_WEEK: null,
  TAB_SWITCH_THIS_MONTH: null,
  TAB_SWITCH_ALL: null,
  BOTS_WITH_INSIGHTS: null,
  INSIGHTS_LOADING: null,
  INSIGHTS_DATA: null,

  BOT_STATUS_INSIGHTS_LOADING: null,
  BOT_STATUS_NO_INSIGHTS_AVAILABLE: null,
  BOT_STATUS_INSIGHTS_LOADED: null,
  BOT_STATUS_NO_BOT: null
});